
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:

logger:
  default: info
  logs:
    homeassistant.components.zha: info
    bellows.uart: info

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
